print("*****************************************************************")
print(sub(".*=", "", commandArgs()))
print(sub(".*=", "", commandArgs()[4]))
print(paste("Script start time:", Sys.time()))
print("*****************************************************************")
print(paste("Script end time:", Sys.time()))
print("*****************************************************************")