print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("Running schedule.r")
a <- Sys.time()
print(paste("Schedule start time:", Sys.time()))
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")

source("/home/cloudera/Desktop/codes/SAM/package.r")
source("/home/cloudera/Desktop/codes/SAM/load_kyc.r")
source("/home/cloudera/Desktop/codes/SAM/load_tran.r")
source("/home/cloudera/Desktop/codes/SAM/kyc_clustering.r")
source("/home/cloudera/Desktop/codes/SAM/tran_clustering.r")
source("/home/cloudera/Desktop/codes/SAM/sort.r")
source("/home/cloudera/Desktop/codes/SAM/compare.r")
source("/home/cloudera/Desktop/codes/SAM/fill_alerts.r")
source("/home/cloudera/Desktop/codes/SAM/report.r")

b <- Sys.time()
print(paste("Schedule end time:", Sys.time()))
print(b - a)
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")